id: compare-kafka

name: Compare Kafka

description: Compare Kafka

runtime: bash

entrypoint: script.sh

version: 1.0.0

inputs:
  - name: prod-csv
    required: true
  - name: dr-csv
    required: true
